### ISSUE TITLE
request error 导致插件报错

### ISSUE THREAD

**Issue by jianglin-wu** [highso-fe/egg-exporter#5]
错误堆栈如下：

```
/data/frontend/fe-node-staticize-render/node_modules/egg-exporter/lib/metrics/http_server.js:70
    const { method, path } = ctx;
            ^

TypeError: Cannot destructure property `method` of 'undefined' or 'null'.
    at Application.app.on (/data/frontend/fe-node-staticize-render/node_modules/egg-exporter/lib/metrics/http_server.js:70:30)
    at Application.emit (events.js:187:15)
    at Lifecycle.EggCore.lifecycle.on.err (/data/frontend/fe-node-staticize-render/node_modules/egg-core/lib/egg.js:106:44)
    at Lifecycle.emit (events.js:182:13)
    at Ready.ready.on.err (/data/frontend/fe-node-staticize-render/node_modules/egg-core/lib/lifecycle.js:238:35)
    at Ready.emit (events.js:187:15)
    at Ready.readyDone (/data/frontend/fe-node-staticize-render/node_modules/ready-callback/lib/ready.js:118:19)
    at Immediate.setImmediate (/data/frontend/fe-node-staticize-render/node_modules/ready-callback/lib/ready.js:97:31)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
```

**Comment by jianglin-wu** [comment]
已解决
